version: "3.7"
services:
        dev:
                build: 
                        context: .
                        dockerfile: Dockerfile.dev
                image: net.ofnir/openresty-fennel-rest-api-dev
                volumes:
                        - "./src:/app:z"
                        - "./dev:/etc/nginx/conf.d:z"
                ports:
                        - "127.0.0.1:8080:8080"
